# filename: templates/typescript-basic-webserver/manifests/kustomization.yaml
# Kustomization configuration for Kubernetes resources
#
# This file serves several important purposes:
# 1. Defines which Kubernetes manifest files should be applied
# 2. Enables ArgoCD to properly sync and manage the application
# 3. Configures common labels and annotations for all resources
# 4. Allows for environment-specific customizations
#
# Template variables:
# terchris - Will be replaced with the GitHub username from the repository URL
# urb-dev-typescript-hello-world - Will be replaced with the actual repository name

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference all manifest files that should be applied
resources:
  - deployment.yaml
  - ingress.yaml

# Add common labels to all resources
commonLabels:
  app: "urb-dev-typescript-hello-world"
  owner: "terchris"
  managed-by: argocd

# Add common annotations to all resources
commonAnnotations:
  description: "Deployed via Urbalurba infrastructure"
  repository: "https://github.com/terchris/urb-dev-typescript-hello-world"